### ISSUE TITLE
how to change warpctc with mx.contrib.sym.ctc_loss ?

### ISSUE THREAD

**Issue by BackT0TheFuture** [xinghedyc/mxnet-cnn-lstm-ctc-ocr#3]
Hi,there
is it possible to change warpctc with mx.contrib.sym.ctc_loss ?
thx!

**Comment by xinghedyc** [comment]
I simply use warpctc in mxnet/example and I have not tried the contrib.sym.ctc_loss. I find out they seem to be incompatible a month ago. However, you may have a try!

**Comment by BackT0TheFuture** [comment]
got it! thx!
